Script started on 2023-05-04 00:03:01-06:00 [TERM="xterm-256color" TTY="/dev/pts/5" COLUMNS="207" LINES="17"]
]0;spear@mint-dell: ~/Documents/cse113/labfinal[01;32mspear@mint-dell[00m:[01;34m~/Documents/cse113/labfinal[00m$ make
gcc -g -Wall -c  logic.c 
gcc -g -Wall -I/usr/include/SDL2 -D_REENTRANT life.c logic.o sdl.o -o life -lSDL2 -lm
]0;spear@mint-dell: ~/Documents/cse113/labfinal[01;32mspear@mint-dell[00m:[01;34m~/Documents/cse113/labfinal[00m$ ./[K[Kvalgrind --show-reachable=yes --leak-check=full ./life
==117299== Memcheck, a memory error detector
==117299== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==117299== Using Valgrind-3.15.0 and LibVEX; rerun with -h for copyright info
==117299== Command: ./life
==117299== 
include -H for help
==117299== 
==117299== HEAP SUMMARY:
==117299==     in use at exit: 0 bytes in 0 blocks
==117299==   total heap usage: 2 allocs, 2 frees, 1,061 bytes allocated
==117299== 
==117299== All heap blocks were freed -- no leaks are possible
==117299== 
==117299== For lists of detected and suppressed errors, rerun with: -s
==117299== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
]0;spear@mint-dell: ~/Documents/cse113/labfinal[01;32mspear@mint-dell[00m:[01;34m~/Documents/cse113/labfinal[00m$ exit
exit

Script done on 2023-05-04 00:03:16-06:00 [COMMAND_EXIT_CODE="0"]
