.TH "color_t" 3 "Thu May 4 2023" "Conway's Game of Life - CSE113 - Maya Savino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
color_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "unsigned char \fBred\fP"
.br
.ti -1c
.RI "unsigned char \fBgreen\fP"
.br
.ti -1c
.RI "unsigned char \fBblue\fP"
.br
.ti -1c
.RI "unsigned int \fBvalue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Conway's Game of Life - CSE113 - Maya Savino from the source code\&.
