.TH "sdl.h" 3 "Thu May 4 2023" "Conway's Game of Life - CSE113 - Maya Savino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sdl.h \- logic for game of life  

.SH SYNOPSIS
.br
.PP
\fC#include <SDL2/SDL\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBcolor_t\fP"
.br
.ti -1c
.RI "struct \fBsdl_info_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBinit_sdl_info\fP (struct \fBsdl_info_t\fP *sdl_info, int width, int height, int sprite_size, unsigned int red, unsigned int green, unsigned int blue)"
.br
.ti -1c
.RI "void \fBsdl_render_life\fP (struct \fBsdl_info_t\fP *sdl_info, unsigned char **life)"
.br
.ti -1c
.RI "void \fBsdl_test\fP (struct \fBsdl_info_t\fP *sdl_info, int m, int n)"
.br
.in -1c
.SH "Detailed Description"
.PP 
logic for game of life 


.PP
\fBAuthor\fP
.RS 4
Maya Savino
.RE
.PP
\fBDate\fP
.RS 4
05/03/2023
.RE
.PP
Assignment: Final - Conway's Game of Life
.PP
@bugs none
.PP
\fBTodo\fP
.RS 4
none
.RE
.PP
.PP
\fBParameters\fP
.RS 4
\fIinit_sdl_info\fP initialize with given info 
.br
\fIsdl_render_life\fP render game of life 
.br
\fIsdl_test\fP for testing 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Conway's Game of Life - CSE113 - Maya Savino from the source code\&.
