.TH "sdl_info_t" 3 "Thu May 4 2023" "Conway's Game of Life - CSE113 - Maya Savino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sdl_info_t
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "SDL_Surface * \fBscreen\fP"
.br
.ti -1c
.RI "SDL_Window * \fBwindow\fP"
.br
.ti -1c
.RI "SDL_Renderer * \fBrenderer\fP"
.br
.ti -1c
.RI "SDL_Texture * \fBtexture\fP"
.br
.ti -1c
.RI "struct \fBcolor_t\fP \fBcolor\fP"
.br
.ti -1c
.RI "int \fBwidth\fP"
.br
.ti -1c
.RI "int \fBheight\fP"
.br
.ti -1c
.RI "int \fBsprite_size\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for Conway's Game of Life - CSE113 - Maya Savino from the source code\&.
