.TH "todo" 3 "Thu May 4 2023" "Conway's Game of Life - CSE113 - Maya Savino" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 

.IP "\fBFile \fBlife\&.c\fP \fP" 1c
none 
.PP
fix -x option (for randomizing colors) 
.IP "\fBFile \fBlogic\&.c\fP \fP" 1c
none 
.IP "\fBFile \fBsdl\&.h\fP \fP" 1c
none
.PP

